import { useState } from 'react';
import SwapHorizIcon from '@mui/icons-material/SwapHoriz';
import StraightenIcon from '@mui/icons-material/Straighten';
import { Alert, Box, Button, Card, CardContent, CircularProgress, Container, FormControl, InputAdornment, InputLabel, MenuItem, Select, Stack, TextField, Typography } from '@mui/material';

const categories = {
  length: { label: 'Longueur', units: [{ id: 'feet', label: 'Pieds' }, { id: 'meters', label: 'Mètres' }] },
  temperature: { label: 'Température', units: [{ id: 'celsius', label: 'Celsius (°C)' }, { id: 'fahrenheit', label: 'Fahrenheit (°F)' }] },
  weight: { label: 'Poids', units: [{ id: 'kilograms', label: 'Kilogrammes (kg)' }, { id: 'pounds', label: 'Livres (lb)' }] }
};

export default function App() {
  const [category, setCategory] = useState('length'); const [value, setValue] = useState(''); const [from, setFrom] = useState('feet'); const [to, setTo] = useState('meters'); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const selected = categories[category];
  const unitLabel = id => selected.units.find(unit => unit.id === id)?.label || id;
  function changeCategory(event) { const next = event.target.value; setCategory(next); setFrom(categories[next].units[0].id); setTo(categories[next].units[1].id); setResult(null); setError(''); }
  function swapUnits() { setFrom(to); setTo(from); setResult(null); }
  async function convert(event) { event.preventDefault(); setError(''); setResult(null); if (value.trim() === '' || !Number.isFinite(Number(value))) { setError('Veuillez saisir une valeur numérique valide.'); return; } setLoading(true); try { const response = await fetch('/api/convert', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ value: Number(value), from, to, category }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'La conversion a échoué.'); setResult(data.result); } catch (requestError) { setError(requestError.message || 'Impossible de joindre le serveur.'); } finally { setLoading(false); } }
  return <Box sx={{ minHeight: '100vh', display: 'flex', alignItems: 'center', py: 4 }}><Container maxWidth="sm"><Card elevation={5}><CardContent sx={{ p: { xs: 3, sm: 5 } }}><Stack component="form" spacing={3} onSubmit={convert}><Box textAlign="center"><StraightenIcon color="primary" sx={{ fontSize: 48, mb: 1 }} /><Typography component="h1" variant="h4" fontWeight={700}>Convertisseur d’unités</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>Convertissez des longueurs, températures et poids.</Typography></Box><FormControl fullWidth><InputLabel id="category-label">Type de conversion</InputLabel><Select labelId="category-label" label="Type de conversion" value={category} onChange={changeCategory}>{Object.entries(categories).map(([id, item]) => <MenuItem key={id} value={id}>{item.label}</MenuItem>)}</Select></FormControl><TextField autoFocus fullWidth label="Valeur" onChange={event => setValue(event.target.value)} placeholder="Ex. : 10" type="number" value={value} InputProps={{ inputMode: 'decimal', endAdornment: <InputAdornment position="end">{unitLabel(from)}</InputAdornment> }} /><Stack direction="row" spacing={1.5} alignItems="center"><FormControl fullWidth><InputLabel id="from-label">De</InputLabel><Select labelId="from-label" label="De" value={from} onChange={event => setFrom(event.target.value)}>{selected.units.map(unit => <MenuItem key={unit.id} value={unit.id}>{unit.label}</MenuItem>)}</Select></FormControl><Button aria-label="Inverser les unités" onClick={swapUnits} sx={{ minWidth: 48 }}><SwapHorizIcon /></Button><FormControl fullWidth><InputLabel id="to-label">Vers</InputLabel><Select labelId="to-label" label="Vers" value={to} onChange={event => setTo(event.target.value)}>{selected.units.map(unit => <MenuItem key={unit.id} value={unit.id}>{unit.label}</MenuItem>)}</Select></FormControl></Stack><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1.5}><Button disabled={loading} fullWidth size="large" startIcon={loading ? <CircularProgress color="inherit" size={20} /> : <SwapHorizIcon />} type="submit" variant="contained">{loading ? 'Conversion…' : 'Convertir'}</Button><Button disabled={loading} fullWidth onClick={() => { setValue(''); setResult(null); setError(''); }} size="large" variant="outlined">Effacer</Button></Stack>{error && <Alert severity="error">{error}</Alert>}{result !== null && <Alert icon={<StraightenIcon fontSize="inherit" />} severity="success"><Typography fontWeight={700} variant="h6">{value} {unitLabel(from)} = {result} {unitLabel(to)}</Typography></Alert>}</Stack></CardContent></Card></Container></Box>;
}
